import { useState } from "react";
import Header from "../components/Header";
import FootageModal from "../components/ui/footageModal";
import Lanao from "../assets/Footage/lanao.mp4"
import Cebu from "../assets/Footage/cebu.mp4"


export default function Footage() {
  const [modalOpen, setModalOpen] = useState(false);
  const [selectedCard, setSelectedCard] = useState<any>(null);

  const videoCards = [
    {
      id: 1,
      title: "Lanao Earthquake",
      date: "April 1, 1955",
      location: "Lanao del Sur, Mindanao",
      video: Lanao,
      description:
        "Strike-slip event on the Cotabato–Sindangan Fault system. Affected areas in northern & central Mindanao and southern Visayas.",
      modalContent: (
        <div>
          <video
            src={Lanao} 
            controls
            className="w-full rounded-lg mb-6"
          />
          <h3 className="font-bold text-xl mb-3">Overview</h3>
          <p className="mb-2">
            <strong>Magnitude:</strong> Mw 7.4 (corrected from initial Mw 6.9)
          </p>
          <p className="mb-2">
            <strong>Depth:</strong> 25 km (corrected from 8 km)
          </p>
          <p>
            <strong>Tectonic Setting:</strong> Generated from the Philippine
            Trench subduction zone, offshore Surigao del Sur.
          </p>

        <h4 className="font-bold text-xl mb-3">Maximum Intensity (PHIVOLCS)</h4>
        <p className="mb-2">
            <strong>Intensity VI:</strong> Maco, Monkayo (Davao de Oro)
          </p>
          <p className="mb-2">
            <strong>Intensity V:</strong> Nabunturan (Davao de Oro), Tagum (Davao del Norte), Davao City
          </p>
           <p className="mb-2">
            <strong>Intensity IV:</strong> Digos City, Magsaysay (Davao del Sur)
          </p>
          <p className="mb-2">
            <strong>Intensity III-II:</strong> Felt in multiple provinces (Davao Occidental, Agusan del Sur, Davao Oriental, Misamis Oriental, etc.)
          </p>
        </div>
      ),
    },
    
    {
      id: 2,
      title: "Cebu, Philippines Earthquake",
      date: "September 30, 2025",
      location: "northeast of Bogo City, Cebu Province",
      video: Cebu,
      description:
        "A magnitude 6.9 earthquake struck northern Cebu on September 30, 2025, causing deaths, damage, and displacement across Central Visayas.",
      modalContent: (
        <div>
          <video
            src={Cebu} 
            controls
            className="w-full rounded-lg mb-6"
          />
          <h3 className="font-bold text-xl mb-3">Overview</h3>
          <p className="mb-2">
            <strong>Magnitude:</strong> Mw 6.9 
          </p>
          <p className="mb-2">
            <strong>Depth:</strong> 5 km
          </p>
          <p>
        <strong>Tectonic Setting:</strong> Generated by active fault movement within the Philippine Mobile Belt, near the Central Cebu Fault System.
        </p>
        
        <h4 className="font-bold text-xl mb-3">Maximum Intensity (PHIVOLCS)</h4>
        <p className="mb-2">
        <strong>Intensity VI:</strong> Cebu City, Villaba (Leyte)
        </p>
        <p className="mb-2">
        <strong>Intensity V:</strong> Bogo City (Cebu), San Remigio (Cebu), Ormoc City (Leyte)
        </p>
        <p className="mb-2">
        <strong>Intensity IV:</strong> Tacloban City (Leyte), Catbalogan (Samar), Dumaguete City (Negros Oriental)
        </p>
        <p className="mb-2">
        <strong>Intensity III-II:</strong> Felt in Iloilo, Bacolod (Negros Occidental), Southern Leyte, Samar provinces
        </p>

        <h5 className="font-bold text-xl mb-3">Casualty & Injury</h5>
        <ul className="list-disc ml-6">
        <li><strong>At least 72 deaths</strong> reported as of October 2, 2025.</li>
        <li><strong>Hundreds injured</strong> (estimates between 294–559 depending on official updates).</li>
        <li>Casualties concentrated in Bogo, San Remigio, and Medellin municipalities.</li>
        <li>Fatal incidents included a roof collapse during a basketball game and landslides triggered by the quake.</li>
        </ul>
        </div>
      ),
    },
  ];

  const openModal = (card: any) => {
    setSelectedCard(card);
    setModalOpen(true);
  };

  const closeModal = () => {
    setSelectedCard(null);
    setModalOpen(false);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Header />

      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <h1 className="text-3xl font-bold mb-4">Video Gallery</h1>
        <p className="text-gray-600 mb-8">
          Experience real earthquake footage from across the Philippines. Tap to
          learn more about each event and how it affected local communities.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {videoCards.map((card) => (
            <div
              key={card.id}
              className="bg-white rounded-xl shadow hover:shadow-lg transition p-4 flex flex-col"
            >
              {/* Video Preview */}
              <video
                src={card.video}
                className="w-full h-48 object-cover rounded-md mb-4"
                controls={false}
                muted
                loop
              />

              <p className="text-sm text-gray-500">{card.date}</p>
              <p className="text-sm text-gray-500">{card.location}</p>
              <h3 className="text-lg font-semibold mt-2">{card.title}</h3>
              <p className="text-sm text-gray-700 mt-1">{card.description}</p>

              <button
                onClick={() => openModal(card)}
                className="mt-4 px-4 py-2 bg-quake-purple text-white rounded-lg hover:bg-quake-dark-blue transition"
              >
                View More
              </button>
            </div>
          ))}
        </div>
      </main>

      {selectedCard && (
        <FootageModal
          isOpen={modalOpen}
          onClose={closeModal}
          title={selectedCard.title}
          description={selectedCard.date + " • " + selectedCard.location}
          content={selectedCard.modalContent}
        />
      )}
    </div>
  );
}
