[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Map analysis - dedicated function
[[redirects]]
  from = "/map"
  to = "/.netlify/functions/map"
  status = 200

# Earthquake specific endpoints
[[redirects]]
  from = "/api/earthquakes/search"
  to = "/.netlify/functions/earthquakes-search"
  status = 200

[[redirects]]
  from = "/api/earthquakes/country"
  to = "/.netlify/functions/earthquakes-by-country"
  status = 200

[[redirects]]
  from = "/api/earthquakes"
  to = "/.netlify/functions/earthquakes"
  status = 200

# All other API routes (news, footage, etc.)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200