[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/map/*"
  to = "/.netlify/functions/map"
  status = 200

[[redirects]]
  from = "/api/earthquakes/*"
  to = "/.netlify/functions/earthquakes"
  status = 200