[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]

[dev]
  command = "npm run dev"
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200