[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/map"
  to = "/.netlify/functions/map/map"
  status = 200

[[redirects]]
  from = "/map/*"
  to = "/.netlify/functions/map/map/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/map/api/:splat"
  status = 200